version: "3.9"

services:
  dearlavion-authentication-service:
    image: dearlavion-authentication-service:latest
    ports:
      - "8081:8080"
    networks:
      - dearlavion-net

  dearlavion-core-service:
    image: dearlavion-core-service:latest
    ports:
      - "8082:8080"
    networks:
      - dearlavion-net

  dearlavion-web-ui:
    build: ./dearlavion-web-ui
    networks:
      - dearlavion-net
    depends_on:
      - dearlavion-authentication-service
      - dearlavion-core-service

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dearlavion-web-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - dearlavion-web-ui
      - dearlavion-authentication-service
      - dearlavion-core-service
    networks:
      - dearlavion-net

networks:
  dearlavion-net:
    driver: bridge
