---
- name: Ensure Docker is installed
  import_role:
    name: docker

- name: Build and run Docker Compose
  community.docker.docker_compose:
    project_src: "{{ app_path }}"
    build: yes
    state: present
    restarted: yes
