---
- name: Deploy Angular UI + Nginx
  hosts: localhost
  become: yes

  vars:
    ui_project_path: "/Users/alysson/dev/frontend/dearlavion-web-ui"
    #nginx_web_root: "/var/www/dearlavion"
    nginx_web_root: "/opt/homebrew/var/www/dearlavion/browser"
    nginx_conf_dir: "/opt/homebrew/etc/nginx/servers"
    n8n_port: 5678
    core_port: 8082
    auth_port: 8081
    ansible_user: alysson

  roles:
    - frontend