# General environment settings
use_ngrok: false
compose_file: docker-compose.dev.yml
app_path: /home/baish/dearlavion-projects/dearlavion-app  # Absolute path on DEV server

# Optional: Docker Compose service names
auth_service: dearlavion-authentication-service
core_service: dearlavion-core-service
web_ui_service: dearlavion-web-ui
