# General environment settings
use_ngrok: false
compose_file: docker-compose.dev.yml
project_path: /home/baish/dearlavion-projects  # Absolute path on DEV server
app_path: "{{ project_path }}/dearlavion-app"
email: "dearlavion@gmail.com"

# Optional: Docker Compose service names
auth_service: dearlavion-authentication-service
core_service: dearlavion-core-service
web_ui_service: dearlavion-web-ui
web_ui_port: 80
auth_port: 8081
core_port: 8082
server_names:
  - dearlavion.site
  - www.dearlavion.site
