# app-deploy.yml
name: Deploy Application (DEV)

on:
  workflow_dispatch:
    inputs:
      service:
        description: auth | core | web-ui
        required: true
      env:
        default: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEARLAVION_PAT }}

      - name: Build & Push Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ghcr.io/dearlavion/dearlavion-${{ inputs.service }}-service:${{ inputs.env }} \
            .

  deploy:
    needs: build-and-deploy
    uses: ./.github/workflows/common-ansible.yml
    with:
      target: ${{ inputs.service }}
      env: ${{ inputs.env }}
    secrets: inherit
